export const ERROR_CODES = {
  VALIDATION: {
    INVALID_INPUT: 'ERR_VALIDATION_INVALID_INPUT',
    REQUIRED_FIELD: 'ERR_VALIDATION_REQUIRED_FIELD',
    INVALID_FORMAT: 'ERR_VALIDATION_INVALID_FORMAT',
    OUT_OF_RANGE: 'ERR_VALIDATION_OUT_OF_RANGE',
  },
  AUTHENTICATION: {
    INVALID_PASSWORD: 'ERR_AUTH_INVALID_PASSWORD',
    SESSION_EXPIRED: 'ERR_AUTH_SESSION_EXPIRED',
    SESSION_NOT_FOUND: 'ERR_AUTH_SESSION_NOT_FOUND',
    TOKEN_INVALID: 'ERR_AUTH_TOKEN_INVALID',
    BRUTE_FORCE: 'ERR_AUTH_BRUTE_FORCE',
  },
  AUTHORIZATION: {
    PERMISSION_DENIED: 'ERR_AUTHZ_PERMISSION_DENIED',
    WORKSPACE_MISMATCH: 'ERR_AUTHZ_WORKSPACE_MISMATCH',
    ROLE_REQUIRED: 'ERR_AUTHZ_ROLE_REQUIRED',
  },
  NOT_FOUND: {
    WORKSPACE: 'ERR_NOT_FOUND_WORKSPACE',
    SERVER: 'ERR_NOT_FOUND_SERVER',
    RESOURCE: 'ERR_NOT_FOUND_RESOURCE',
  },
  CONFLICT: {
    DUPLICATE: 'ERR_CONFLICT_DUPLICATE',
    LOCKED: 'ERR_CONFLICT_LOCKED',
    VERSION_MISMATCH: 'ERR_CONFLICT_VERSION_MISMATCH',
  },
  INFRASTRUCTURE: {
    DATABASE: 'ERR_INFRA_DATABASE',
    REDIS: 'ERR_INFRA_REDIS',
    QUEUE: 'ERR_INFRA_QUEUE',
    WEBSOCKET: 'ERR_INFRA_WEBSOCKET',
  },
  PROVIDER: {
    WHATSAPP: 'ERR_PROVIDER_WHATSAPP',
    TELEGRAM: 'ERR_PROVIDER_TELEGRAM',
    TUNNEL: 'ERR_PROVIDER_TUNNEL',
    AI: 'ERR_PROVIDER_AI',
    GITHUB: 'ERR_PROVIDER_GITHUB',
  },
  INTERNAL: {
    UNEXPECTED: 'ERR_INTERNAL_UNEXPECTED',
    NOT_IMPLEMENTED: 'ERR_INTERNAL_NOT_IMPLEMENTED',
    TIMEOUT: 'ERR_INTERNAL_TIMEOUT',
  },
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];
