import { type ReactNode } from 'react';
import { cn } from '../../utils/cn.js';
import { Container, Cpu, Activity, Server, Database, Globe, Info, Search } from 'lucide-react';
import { SkeletonBlock } from '../shared/Skeleton.js';
const badgeColors: Record<string, string> = { primary: 'bg-[hsl(var(--color-primary))]/10 text-[hsl(var(--color-primary))]', success: 'bg-[hsl(var(--color-success))]/10 text-[hsl(var(--color-success))]', warning: 'bg-[hsl(var(--color-warning))]/10 text-[hsl(var(--color-warning))]', danger: 'bg-[hsl(var(--color-danger))]/10 text-[hsl(var(--color-danger))]', info: 'bg-[hsl(var(--color-accent))]/10 text-[hsl(var(--color-accent))]' };
export function DockerBadge({ label, variant = 'primary', className }: { label: string; variant?: string; className?: string }) { return <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium', badgeColors[variant], className)}>{label}</span>; }
const statusStyles: Record<string, { color: string; dot: string; label: string }> = { running: { color: 'text-[hsl(var(--color-success))]', dot: 'bg-[hsl(var(--color-success))]', label: 'Running' }, stopped: { color: 'text-[hsl(var(--color-muted))]', dot: 'bg-[hsl(var(--color-muted))]', label: 'Stopped' }, exited: { color: 'text-[hsl(var(--color-danger))]', dot: 'bg-[hsl(var(--color-danger))]', label: 'Exited' }, paused: { color: 'text-[hsl(var(--color-warning))]', dot: 'bg-[hsl(var(--color-warning))]', label: 'Paused' } };
export function DockerStatus({ status, className }: { status: string; className?: string }) { if (!(status in statusStyles)) return <span className={cn('text-xs text-[hsl(var(--color-muted))]', className)}>{status}</span>; const s = statusStyles[status]; return <span className={cn('inline-flex items-center gap-1.5 text-xs font-medium', s.color, className)}><span className={cn('h-1.5 w-1.5 rounded-full', s.dot)} aria-hidden="true" />{s.label}</span>; }
export function DockerEmptyState({ title = 'No Docker data', description = 'No Docker data is available.', className }: { title?: string; description?: string; className?: string }) { return <div className={cn('flex min-h-32 flex-col items-center justify-center gap-2 p-6', className)}><Container className="h-8 w-8 text-[hsl(var(--color-muted))]" aria-hidden="true" /><p className="text-sm font-medium text-[hsl(var(--color-text))]">{title}</p><p className="text-xs text-[hsl(var(--color-muted))] text-center max-w-sm">{description}</p></div>; }
export function DockerCard({ title, icon, children, className }: { title: string; icon: ReactNode; children: ReactNode; className?: string }) { return <section className={cn('rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))]', className)} aria-label={title}><div className="flex items-center gap-2 border-b border-[hsl(var(--color-border))] px-4 py-3"><span className="text-[hsl(var(--color-muted))]" aria-hidden="true">{icon}</span><h3 className="text-sm font-semibold text-[hsl(var(--color-text))]">{title}</h3></div><div className="p-4">{children}</div></section>; }
function formatTimeAgo(iso: string): string { const mins = Math.floor((Date.now() - new Date(iso).getTime()) / 60000); if (mins < 1) return 'just now'; if (mins < 60) return String(mins) + 'm ago'; const hrs = Math.floor(mins / 60); if (hrs < 24) return String(hrs) + 'h ago'; return String(Math.floor(hrs / 24)) + 'd ago'; }
export function DockerOverview({ containerCount, runningCount, stoppedCount, totalCpu, totalMemory }: { containerCount: number; runningCount: number; stoppedCount: number; totalCpu: number; totalMemory: number; className?: string }) {
  const items = [
    { label: 'Containers', value: String(containerCount), icon: Container, color: 'text-[hsl(var(--color-primary))]' },
    { label: 'Running', value: String(runningCount), icon: Activity, color: 'text-[hsl(var(--color-success))]' },
    { label: 'Stopped', value: String(stoppedCount), icon: Server, color: stoppedCount > 0 ? 'text-[hsl(var(--color-muted))]' : 'text-[hsl(var(--color-muted))]' },
    { label: 'Total CPU', value: totalCpu.toFixed(1) + '%', icon: Cpu, color: 'text-[hsl(var(--color-accent))]' },
    { label: 'Total RAM', value: totalMemory.toFixed(1) + '%', icon: Database, color: totalMemory >= 80 ? 'text-[hsl(var(--color-danger))]' : 'text-[hsl(var(--color-warning))]' },
  ];
  return <div className={cn('flex flex-wrap gap-4')}>{items.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))] px-4 py-3 flex-1 min-w-28"><item.icon className={cn('h-5 w-5 shrink-0', item.color)} aria-hidden="true" /><div><p className="text-xs text-[hsl(var(--color-muted))]">{item.label}</p><p className="text-sm font-semibold text-[hsl(var(--color-text))]">{item.value}</p></div></div>)}</div>;
}
export function DockerContainerCard({ container }: { container: { id: string; name: string; image: string; status: string; cpuPercent: number; memoryPercent: number; restartCount: number; ports: string; created: string } }) {
  return <div className="rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))] p-4 transition-all hover:border-[hsl(var(--color-border))]/80 hover:bg-[hsl(var(--color-border))]/30"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2 min-w-0"><Container className="h-4 w-4 shrink-0 text-[hsl(var(--color-muted))]" aria-hidden="true" /><span className="text-sm font-semibold text-[hsl(var(--color-text))] truncate">{container.name}</span><DockerStatus status={container.status} /></div><span className="text-xs text-[hsl(var(--color-muted))] shrink-0">{String(container.restartCount)} restarts</span></div><p className="text-xs text-[hsl(var(--color-muted))] mb-2">{container.image}</p><div className="flex items-center gap-3 text-[10px] text-[hsl(var(--color-muted))]"><span className="flex items-center gap-1"><Cpu className="h-3 w-3" aria-hidden="true" />{container.cpuPercent.toFixed(1)}%</span><span className="flex items-center gap-1"><Activity className="h-3 w-3" aria-hidden="true" />{container.memoryPercent.toFixed(1)}%</span><span className="flex items-center gap-1"><Globe className="h-3 w-3" aria-hidden="true" />{container.ports}</span></div></div>;
}
export function DockerStatsCard({ containers, isLoading }: { containers: { cpuPercent: number; memoryPercent: number }[]; isLoading?: boolean }) {
  if (isLoading) return <DockerCard title="Stats" icon={<Activity className="h-4 w-4" />}><SkeletonBlock lines={4} /></DockerCard>;
  const avgCpu = containers.length > 0 ? containers.reduce((s, c) => s + c.cpuPercent, 0) / containers.length : 0;
  const avgMem = containers.length > 0 ? containers.reduce((s, c) => s + c.memoryPercent, 0) / containers.length : 0;
  return <DockerCard title="Stats" icon={<Activity className="h-4 w-4" />}><div className="space-y-3"><div><p className="text-xs text-[hsl(var(--color-muted))] mb-1">Avg CPU</p><div className="h-2 rounded-full bg-[hsl(var(--color-border))] overflow-hidden"><div className={cn('h-full rounded-full', avgCpu >= 80 ? 'bg-[hsl(var(--color-danger))]' : avgCpu >= 50 ? 'bg-[hsl(var(--color-warning))]' : 'bg-[hsl(var(--color-primary))]')} style={{ width: String(avgCpu) + '%' }} role="progressbar" aria-valuenow={Math.round(avgCpu)} aria-valuemin={0} aria-valuemax={100} aria-label={'Avg CPU: ' + avgCpu.toFixed(1) + '%'} /></div><p className="text-xs text-[hsl(var(--color-text))] mt-1">{avgCpu.toFixed(1)}%</p></div><div><p className="text-xs text-[hsl(var(--color-muted))] mb-1">Avg Memory</p><div className="h-2 rounded-full bg-[hsl(var(--color-border))] overflow-hidden"><div className={cn('h-full rounded-full', avgMem >= 80 ? 'bg-[hsl(var(--color-danger))]' : avgMem >= 50 ? 'bg-[hsl(var(--color-warning))]' : 'bg-[hsl(var(--color-primary))]')} style={{ width: String(avgMem) + '%' }} role="progressbar" aria-valuenow={Math.round(avgMem)} aria-valuemin={0} aria-valuemax={100} aria-label={'Avg Memory: ' + avgMem.toFixed(1) + '%'} /></div><p className="text-xs text-[hsl(var(--color-text))] mt-1">{avgMem.toFixed(1)}%</p></div></div></DockerCard>;
}
export function DockerLogsCard({ name }: { name: string }) { return <DockerCard title="Recent Logs" icon={<Info className="h-4 w-4" />}><div className="space-y-1 text-xs font-mono">{Array.from({ length: 5 }).map((_, i) => <p key={i} className="text-[hsl(var(--color-muted))] truncate">{'[' + String(24 - i) + ':00:00] ' + (i === 0 ? 'INFO: Container ' + name + ' health check passed' : i === 1 ? 'INFO: Connection pool refreshed' : i === 2 ? 'WARN: Memory usage above 80%' : i === 3 ? 'INFO: Periodic cleanup completed' : 'INFO: Metrics collected successfully')}</p>)}</div></DockerCard>; }
export function DockerSearch({ value, onChange, placeholder = 'Search containers...', className }: { value: string; onChange: (v: string) => void; placeholder?: string; className?: string }) {
  return <div className={cn('relative', className)}><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[hsl(var(--color-muted))]" aria-hidden="true" /><input type="text" value={value} onChange={(e) => { onChange(e.target.value); }} placeholder={placeholder} className="w-full rounded-lg border border-[hsl(var(--color-border))] bg-[hsl(var(--color-bg))] py-2 pl-9 pr-3 text-sm text-[hsl(var(--color-text))] placeholder:text-[hsl(var(--color-muted))] transition-colors focus:border-[hsl(var(--color-primary))] focus:outline-none focus:ring-1 focus:ring-[hsl(var(--color-primary))]" aria-label={placeholder} /></div>;
}
export function DockerFilter({ options, selected, onChange, className }: { options: { id: string; label: string }[]; selected: string; onChange: (id: string) => void; className?: string }) {
  if (options.length === 0) return null;
  return <div className={cn('flex flex-wrap gap-1.5', className)}>{options.map((opt) => <button key={opt.id} type="button" onClick={() => { onChange(opt.id); }} className={cn('rounded-full px-3 py-1 text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--color-primary))]', selected === opt.id ? 'bg-[hsl(var(--color-primary))] text-white' : 'bg-[hsl(var(--color-bg))] text-[hsl(var(--color-muted))] hover:text-[hsl(var(--color-text))] hover:bg-[hsl(var(--color-border))]')} aria-pressed={selected === opt.id} aria-label={'Filter by ' + opt.label}>{opt.label}</button>)}</div>;
}
export { formatTimeAgo };
