import { type ReactNode } from 'react';
import { cn } from '../../utils/cn.js';
import { GitBranch, GitPullRequest, Activity, Star, GitFork, CircleDot, Shield, Search } from 'lucide-react';
import { SkeletonBlock } from '../shared/Skeleton.js';
const badgeColors: Record<string, string> = { primary: 'bg-[hsl(var(--color-primary))]/10 text-[hsl(var(--color-primary))]', success: 'bg-[hsl(var(--color-success))]/10 text-[hsl(var(--color-success))]', warning: 'bg-[hsl(var(--color-warning))]/10 text-[hsl(var(--color-warning))]', danger: 'bg-[hsl(var(--color-danger))]/10 text-[hsl(var(--color-danger))]', info: 'bg-[hsl(var(--color-accent))]/10 text-[hsl(var(--color-accent))]' };
export function GitHubBadge({ label, variant = 'primary', className }: { label: string; variant?: string; className?: string }) { return <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium', badgeColors[variant], className)}>{label}</span>; }
const statusStyles: Record<string, { color: string; dot: string; label: string }> = { success: { color: 'text-[hsl(var(--color-success))]', dot: 'bg-[hsl(var(--color-success))]', label: 'Success' }, failed: { color: 'text-[hsl(var(--color-danger))]', dot: 'bg-[hsl(var(--color-danger))]', label: 'Failed' }, running: { color: 'text-[hsl(var(--color-primary))]', dot: 'bg-[hsl(var(--color-primary))]', label: 'Running' }, pending: { color: 'text-[hsl(var(--color-warning))]', dot: 'bg-[hsl(var(--color-warning))]', label: 'Pending' }, cancelled: { color: 'text-[hsl(var(--color-muted))]', dot: 'bg-[hsl(var(--color-muted))]', label: 'Cancelled' } };
export function GitHubStatus({ status, className }: { status: string; className?: string }) { if (!(status in statusStyles)) return <span className={cn('text-xs text-[hsl(var(--color-muted))]', className)}>{status}</span>; const s = statusStyles[status]; return <span className={cn('inline-flex items-center gap-1.5 text-xs font-medium', s.color, className)}><span className={cn('h-1.5 w-1.5 rounded-full', s.dot)} aria-hidden="true" />{s.label}</span>; }
export function GitHubEmptyState({ title = 'No GitHub data', description = 'No data available.', className }: { title?: string; description?: string; className?: string }) { return <div className={cn('flex min-h-32 flex-col items-center justify-center gap-2 p-6', className)}><GitBranch className="h-8 w-8 text-[hsl(var(--color-muted))]" aria-hidden="true" /><p className="text-sm font-medium text-[hsl(var(--color-text))]">{title}</p><p className="text-xs text-[hsl(var(--color-muted))] text-center max-w-sm">{description}</p></div>; }
export function GitHubCard({ title, icon, children, className }: { title: string; icon: ReactNode; children: ReactNode; className?: string }) { return <section className={cn('rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))]', className)} aria-label={title}><div className="flex items-center gap-2 border-b border-[hsl(var(--color-border))] px-4 py-3"><span className="text-[hsl(var(--color-muted))]" aria-hidden="true">{icon}</span><h3 className="text-sm font-semibold text-[hsl(var(--color-text))]">{title}</h3></div><div className="p-4">{children}</div></section>; }
function formatTimeAgo(iso: string): string { const mins = Math.floor((Date.now() - new Date(iso).getTime()) / 60000); if (mins < 1) return 'just now'; if (mins < 60) return String(mins) + 'm ago'; const hrs = Math.floor(mins / 60); if (hrs < 24) return String(hrs) + 'h ago'; return String(Math.floor(hrs / 24)) + 'd ago'; }
export function GitHubOverview({ repos, workflows, connected }: { repos: number; workflows: number; connected: boolean; className?: string }) {
  const items = [
    { label: 'Repositories', value: String(repos), icon: GitBranch, color: 'text-[hsl(var(--color-primary))]' },
    { label: 'Workflows', value: String(workflows), icon: Activity, color: 'text-[hsl(var(--color-accent))]' },
    { label: 'Connected', value: connected ? 'Yes' : 'No', icon: Shield, color: connected ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-danger))]' },
  ];
  return <div className={cn('flex flex-wrap gap-4')}>{items.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))] px-4 py-3 flex-1 min-w-28"><item.icon className={cn('h-5 w-5 shrink-0', item.color)} aria-hidden="true" /><div><p className="text-xs text-[hsl(var(--color-muted))]">{item.label}</p><p className="text-sm font-semibold text-[hsl(var(--color-text))]">{item.value}</p></div></div>)}</div>;
}
export function RepositoryCard({ repo }: { repo: { id: number; name: string; owner: string; description: string; language: string; stars: number; forks: number; issues: number; prs: number; branch: string; private: boolean } }) {
  return <div className="rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))] p-4 transition-all hover:border-[hsl(var(--color-border))]/80 hover:bg-[hsl(var(--color-border))]/30"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2 min-w-0"><GitBranch className="h-4 w-4 shrink-0 text-[hsl(var(--color-muted))]" aria-hidden="true" /><span className="text-sm font-semibold text-[hsl(var(--color-text))] truncate">{repo.name}</span><span className="rounded bg-[hsl(var(--color-bg))] px-1.5 py-0.5 text-[10px] text-[hsl(var(--color-muted))]">{repo.private ? 'Private' : 'Public'}</span></div></div><p className="text-xs text-[hsl(var(--color-muted))] mb-2 line-clamp-1">{repo.description}</p><div className="flex items-center gap-3 text-[10px] text-[hsl(var(--color-muted))]"><span className="flex items-center gap-1"><Star className="h-3 w-3" aria-hidden="true" />{String(repo.stars)}</span><span className="flex items-center gap-1"><GitFork className="h-3 w-3" aria-hidden="true" />{String(repo.forks)}</span><span className="flex items-center gap-1"><CircleDot className="h-3 w-3" aria-hidden="true" />{String(repo.issues)}</span><span className="flex items-center gap-1"><GitPullRequest className="h-3 w-3" aria-hidden="true" />{String(repo.prs)}</span><span className="rounded bg-[hsl(var(--color-bg))] px-1.5 py-0.5">{repo.language}</span></div></div>;
}
export function WorkflowCard({ workflow }: { workflow: { id: string; name: string; repo: string; status: string; branch: string; trigger: string; startedAt: string; duration: number } }) {
  return <div className="rounded-lg border border-[hsl(var(--color-border))] p-2.5"><div className="flex items-center justify-between mb-1"><span className="text-xs font-medium text-[hsl(var(--color-text))] truncate">{workflow.name}</span><GitHubStatus status={workflow.status} /></div><div className="flex items-center gap-2 text-[10px] text-[hsl(var(--color-muted))]"><span>{workflow.branch}</span><span>·</span><span>{workflow.trigger}</span><span>·</span><span>{String(workflow.duration)}s</span></div></div>;
}
export function BranchCard({ branch }: { branch: { name: string; protected: boolean; ahead: number; behind: number; lastCommit: string } }) {
  return <div className="flex items-center justify-between rounded-lg border border-[hsl(var(--color-border))] p-2.5"><div className="flex items-center gap-2 min-w-0"><GitBranch className="h-3.5 w-3.5 shrink-0 text-[hsl(var(--color-muted))]" aria-hidden="true" /><span className="text-xs font-medium text-[hsl(var(--color-text))]">{branch.name}</span>{branch.protected && <Shield className="h-3 w-3 text-[hsl(var(--color-success))]" aria-hidden="true" />}</div><div className="flex items-center gap-2 text-[10px] text-[hsl(var(--color-muted))] shrink-0"><span>+{String(branch.ahead)}</span><span>-{String(branch.behind)}</span></div></div>;
}
export function WorkflowHistory({ workflows, isLoading }: { workflows: { id: string; name: string; repo: string; status: string; branch: string; trigger: string; startedAt: string; duration: number }[]; isLoading?: boolean }) {
  if (isLoading) return <GitHubCard title="Workflows" icon={<Activity className="h-4 w-4" />}><SkeletonBlock lines={4} /></GitHubCard>;
  return <GitHubCard title="Workflows" icon={<Activity className="h-4 w-4" />}><div className="space-y-2">{workflows.slice(0, 5).map((w) => <WorkflowCard key={w.id} workflow={w} />)}</div></GitHubCard>;
}
export function GitHubSearch({ value, onChange, placeholder = 'Search repositories...', className }: { value: string; onChange: (v: string) => void; placeholder?: string; className?: string }) {
  return <div className={cn('relative', className)}><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[hsl(var(--color-muted))]" aria-hidden="true" /><input type="text" value={value} onChange={(e) => { onChange(e.target.value); }} placeholder={placeholder} className="w-full rounded-lg border border-[hsl(var(--color-border))] bg-[hsl(var(--color-bg))] py-2 pl-9 pr-3 text-sm text-[hsl(var(--color-text))] placeholder:text-[hsl(var(--color-muted))] transition-colors focus:border-[hsl(var(--color-primary))] focus:outline-none focus:ring-1 focus:ring-[hsl(var(--color-primary))]" aria-label={placeholder} /></div>;
}
export function GitHubFilter({ options, selected, onChange, className }: { options: { id: string; label: string }[]; selected: string; onChange: (id: string) => void; className?: string }) {
  if (options.length === 0) return null;
  return <div className={cn('flex flex-wrap gap-1.5', className)}>{options.map((opt) => <button key={opt.id} type="button" onClick={() => { onChange(opt.id); }} className={cn('rounded-full px-3 py-1 text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--color-primary))]', selected === opt.id ? 'bg-[hsl(var(--color-primary))] text-white' : 'bg-[hsl(var(--color-bg))] text-[hsl(var(--color-muted))] hover:text-[hsl(var(--color-text))] hover:bg-[hsl(var(--color-border))]')} aria-pressed={selected === opt.id} aria-label={'Filter by ' + opt.label}>{opt.label}</button>)}</div>;
}
export { formatTimeAgo };
