import { type ReactNode } from 'react';
import { cn } from '../../utils/cn.js';
import { Globe, Clock, Activity, Shield, RefreshCw, Network, Search, BarChart3, Download, Upload } from 'lucide-react';
import { Skeleton, SkeletonBlock } from '../shared/Skeleton.js';
import { ChartPlaceholder } from './ChartPlaceholder.js';
const badgeColors: Record<string, string> = { primary: 'bg-[hsl(var(--color-primary))]/10 text-[hsl(var(--color-primary))]', success: 'bg-[hsl(var(--color-success))]/10 text-[hsl(var(--color-success))]', warning: 'bg-[hsl(var(--color-warning))]/10 text-[hsl(var(--color-warning))]', danger: 'bg-[hsl(var(--color-danger))]/10 text-[hsl(var(--color-danger))]', info: 'bg-[hsl(var(--color-accent))]/10 text-[hsl(var(--color-accent))]' };
export function TunnelBadge({ label, variant = 'primary', className }: { label: string; variant?: string; className?: string }) { return <span className={cn('inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium', badgeColors[variant], className)}>{label}</span>; }
const statusStyles: Record<string, { color: string; dot: string; label: string }> = { connected: { color: 'text-[hsl(var(--color-success))]', dot: 'bg-[hsl(var(--color-success))]', label: 'Connected' }, disconnected: { color: 'text-[hsl(var(--color-muted))]', dot: 'bg-[hsl(var(--color-muted))]', label: 'Disconnected' }, reconnecting: { color: 'text-[hsl(var(--color-warning))]', dot: 'bg-[hsl(var(--color-warning))]', label: 'Reconnecting' } };
export function TunnelStatus({ status, className }: { status: string; className?: string }) { if (!(status in statusStyles)) return <span className={cn('text-xs text-[hsl(var(--color-muted))]', className)}>{status}</span>; const s = statusStyles[status]; return <span className={cn('inline-flex items-center gap-1.5 text-xs font-medium', s.color, className)}><span className={cn('h-1.5 w-1.5 rounded-full', s.dot)} aria-hidden="true" />{s.label}</span>; }
export function TunnelEmptyState({ title = 'No tunnel data', description = 'No tunnel data is available.', className }: { title?: string; description?: string; className?: string }) { return <div className={cn('flex min-h-32 flex-col items-center justify-center gap-2 p-6', className)}><Globe className="h-8 w-8 text-[hsl(var(--color-muted))]" aria-hidden="true" /><p className="text-sm font-medium text-[hsl(var(--color-text))]">{title}</p><p className="text-xs text-[hsl(var(--color-muted))] text-center max-w-sm">{description}</p></div>; }
export function TunnelCard({ title, icon, children, className }: { title: string; icon: ReactNode; children: ReactNode; className?: string }) { return <section className={cn('rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))]', className)} aria-label={title}><div className="flex items-center gap-2 border-b border-[hsl(var(--color-border))] px-4 py-3"><span className="text-[hsl(var(--color-muted))]" aria-hidden="true">{icon}</span><h3 className="text-sm font-semibold text-[hsl(var(--color-text))]">{title}</h3></div><div className="p-4">{children}</div></section>; }
function formatTimeAgo(iso: string): string { const mins = Math.floor((Date.now() - new Date(iso).getTime()) / 60000); if (mins < 1) return 'just now'; if (mins < 60) return String(mins) + 'm ago'; const hrs = Math.floor(mins / 60); if (hrs < 24) return String(hrs) + 'h ago'; return String(Math.floor(hrs / 24)) + 'd ago'; }
export function TunnelOverview({ overview }: { overview: { status: string; provider: string; domain: string; latency: number; uptime: string; reconnectCount: number; trafficIn: number; trafficOut: number }; className?: string }) {
  const items = [
    { label: 'Provider', value: overview.provider, icon: Globe, color: 'text-[hsl(var(--color-primary))]' },
    { label: 'Domain', value: overview.domain, icon: Network, color: 'text-[hsl(var(--color-accent))]' },
    { label: 'Latency', value: String(overview.latency) + 'ms', icon: Activity, color: overview.latency < 10 ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-warning))]' },
    { label: 'Uptime', value: overview.uptime, icon: Clock, color: 'text-[hsl(var(--color-success))]' },
    { label: 'Reconnects', value: String(overview.reconnectCount), icon: RefreshCw, color: overview.reconnectCount > 0 ? 'text-[hsl(var(--color-warning))]' : 'text-[hsl(var(--color-muted))]' },
  ];
  return <div className={cn('flex flex-wrap gap-4')}>{items.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-xl border border-[hsl(var(--color-border))] bg-[hsl(var(--color-surface))] px-4 py-3 flex-1 min-w-28"><item.icon className={cn('h-5 w-5 shrink-0', item.color)} aria-hidden="true" /><div><p className="text-xs text-[hsl(var(--color-muted))]">{item.label}</p><p className="text-sm font-semibold text-[hsl(var(--color-text))]">{item.value}</p></div></div>)}</div>;
}
export function TunnelStatusCard({ overview, isLoading }: { overview: { status: string; provider: string; domain: string; publicUrl: string; ssl: boolean }; isLoading?: boolean }) {
  if (isLoading) return <TunnelCard title="Status" icon={<Shield className="h-4 w-4" />}><SkeletonBlock lines={4} /></TunnelCard>;
  return <TunnelCard title="Status" icon={<Shield className="h-4 w-4" />}><div className="space-y-2 text-xs"><div className="flex items-center justify-between"><span className="text-[hsl(var(--color-muted))]">Status</span><TunnelStatus status={overview.status} /></div><div className="flex justify-between"><span className="text-[hsl(var(--color-muted))]">Provider</span><span className="text-[hsl(var(--color-text))]">{overview.provider}</span></div><div className="flex justify-between"><span className="text-[hsl(var(--color-muted))]">Domain</span><span className="text-[hsl(var(--color-text))]">{overview.domain}</span></div><div className="flex justify-between"><span className="text-[hsl(var(--color-muted))]">Public URL</span><span className="text-[hsl(var(--color-text))] truncate max-w-48">{overview.publicUrl}</span></div><div className="flex items-center gap-2"><Shield className={cn('h-3 w-3', overview.ssl ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-danger))]')} aria-hidden="true" /><span className={overview.ssl ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-danger))]'}>{overview.ssl ? 'SSL Active' : 'SSL Inactive'}</span></div></div></TunnelCard>;
}
export function TunnelLatencyCard({ latency, isLoading }: { latency: number; isLoading?: boolean }) {
  if (isLoading) return <TunnelCard title="Latency" icon={<Activity className="h-4 w-4" />}><Skeleton className="h-20 w-full" /></TunnelCard>;
  return <TunnelCard title="Latency" icon={<Activity className="h-4 w-4" />}><div className="flex items-center gap-3"><span className="text-3xl font-bold text-[hsl(var(--color-text))]">{String(latency)}</span><span className="text-sm text-[hsl(var(--color-muted))]">ms</span><span className={cn('text-xs font-medium', latency < 10 ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-warning))]')}>{latency < 10 ? 'Excellent' : 'Degraded'}</span></div></TunnelCard>;
}
export function TunnelTrafficCard({ trafficIn, trafficOut, isLoading }: { trafficIn: number; trafficOut: number; isLoading?: boolean }) {
  if (isLoading) return <TunnelCard title="Traffic" icon={<Activity className="h-4 w-4" />}><SkeletonBlock lines={2} /></TunnelCard>;
  function fmt(b: number) { if (b >= 1073741824) return (b / 1073741824).toFixed(1) + ' GB'; if (b >= 1048576) return (b / 1048576).toFixed(1) + ' MB'; return (b / 1024).toFixed(1) + ' KB'; }
  return <TunnelCard title="Traffic (24h)" icon={<BarChart3 className="h-4 w-4" />}><div className="space-y-2 text-xs"><div className="flex items-center gap-2"><Download className="h-3 w-3 text-[hsl(var(--color-success))]" aria-hidden="true" /><span className="text-[hsl(var(--color-muted))]">Inbound:</span><span className="font-medium text-[hsl(var(--color-text))]">{fmt(trafficIn)}</span></div><div className="flex items-center gap-2"><Upload className="h-3 w-3 text-[hsl(var(--color-accent))]" aria-hidden="true" /><span className="text-[hsl(var(--color-muted))]">Outbound:</span><span className="font-medium text-[hsl(var(--color-text))]">{fmt(trafficOut)}</span></div></div></TunnelCard>;
}
export function TunnelReconnectCard({ reconnects, isLoading }: { reconnects: { id: number; timestamp: string; reason: string; duration: number; success: boolean }[]; isLoading?: boolean }) {
  if (isLoading) return <TunnelCard title="Reconnect History" icon={<RefreshCw className="h-4 w-4" />}><SkeletonBlock lines={3} /></TunnelCard>;
  return <TunnelCard title="Reconnect History" icon={<RefreshCw className="h-4 w-4" />}><div className="space-y-2">{reconnects.slice(0, 4).map((r) => <div key={r.id} className="flex items-start justify-between rounded-lg border border-[hsl(var(--color-border))] p-2"><div className="min-w-0 flex-1"><p className="text-xs text-[hsl(var(--color-text))]">{r.reason}</p><p className="text-[10px] text-[hsl(var(--color-muted))]">{formatTimeAgo(r.timestamp)} · {String(r.duration)}s</p></div><span className={cn('shrink-0 text-xs font-medium', r.success ? 'text-[hsl(var(--color-success))]' : 'text-[hsl(var(--color-danger))]')}>{r.success ? 'OK' : 'FAIL'}</span></div>)}</div></TunnelCard>;
}
export function TunnelTimeline({ data, label = 'Tunnel Timeline', isLoading, className }: { data: { timestamp: string; latency: number; traffic: number }[]; label?: string; isLoading?: boolean; className?: string }) {
  if (isLoading) return <div className={cn('space-y-2', className)}><Skeleton className="h-32 w-full" /></div>;
  if (data.length === 0) return <div className={cn('flex min-h-24 items-center justify-center text-sm text-[hsl(var(--color-muted))]', className)}>No data</div>;
  return <div className={cn('space-y-3', className)}><ChartPlaceholder label={label} height="md" variant="line" /></div>;
}
export function TunnelSearch({ value, onChange, placeholder = 'Search tunnels...', className }: { value: string; onChange: (v: string) => void; placeholder?: string; className?: string }) {
  return <div className={cn('relative', className)}><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-[hsl(var(--color-muted))]" aria-hidden="true" /><input type="text" value={value} onChange={(e) => { onChange(e.target.value); }} placeholder={placeholder} className="w-full rounded-lg border border-[hsl(var(--color-border))] bg-[hsl(var(--color-bg))] py-2 pl-9 pr-3 text-sm text-[hsl(var(--color-text))] placeholder:text-[hsl(var(--color-muted))] transition-colors focus:border-[hsl(var(--color-primary))] focus:outline-none focus:ring-1 focus:ring-[hsl(var(--color-primary))]" aria-label={placeholder} /></div>;
}
export function TunnelFilter({ options, selected, onChange, className }: { options: { id: string; label: string }[]; selected: string; onChange: (id: string) => void; className?: string }) {
  if (options.length === 0) return null;
  return <div className={cn('flex flex-wrap gap-1.5', className)}>{options.map((opt) => <button key={opt.id} type="button" onClick={() => { onChange(opt.id); }} className={cn('rounded-full px-3 py-1 text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--color-primary))]', selected === opt.id ? 'bg-[hsl(var(--color-primary))] text-white' : 'bg-[hsl(var(--color-bg))] text-[hsl(var(--color-muted))] hover:text-[hsl(var(--color-text))] hover:bg-[hsl(var(--color-border))]')} aria-pressed={selected === opt.id} aria-label={'Filter by ' + opt.label}>{opt.label}</button>)}</div>;
}
export { formatTimeAgo };
