import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
type Lang = 'en' | 'id' | 'ja';
interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}
const translations: Record<Lang, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.servers': 'Servers',
    'nav.monitoring': 'Monitoring',
    'nav.analytics': 'Analytics',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.automation': 'Automation',
    'nav.backup': 'Backup',
    'nav.tunnel': 'Tunnel',
    'nav.docker': 'Docker',
    'nav.github': 'GitHub',
    'nav.plugins': 'Extensions',
    'nav.security': 'Security',
    'nav.audit': 'Audit',
    'nav.users': 'Users',
    'nav.logs': 'Logs',
    'nav.settings': 'Settings',
    'nav.main': 'Main',
    'nav.management': 'Management',
    'nav.system': 'System',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.retry': 'Retry',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.configure': 'Configure',
    'common.install': 'Install',
    'common.uninstall': 'Uninstall',
    'common.connect': 'Connect',
    'common.disconnect': 'Disconnect',
    'common.refresh': 'Refresh',
    'common.noData': 'No data available',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.timezone': 'Timezone',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.compactMode': 'Compact Mode',
    'settings.animations': 'Animations',
    'settings.autoRefresh': 'Auto Refresh',
    'settings.monitorInterval': 'Monitor Interval',
    'settings.sessionTimeout': 'Session Timeout',
    'settings.twoFactorAuth': 'Two-Factor Auth',
    'settings.telegramBot': 'Telegram Bot',
    'settings.whatsappBot': 'WhatsApp Notifications',
    'settings.telegramToken': 'Bot Token',
    'settings.telegramChatId': 'Chat ID',
    'settings.waPhoneNumber': 'WhatsApp Number',
    'settings.saveSuccess': 'Settings saved successfully',
    'settings.saveFailed': 'Failed to save settings',
    'settings.unsavedChanges': 'You have unsaved changes',
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.bio': 'Bio',
    'profile.department': 'Department',
    'profile.avatar': 'Avatar',
    'profile.security': 'Security',
    'profile.devices': 'Devices',
    'profile.activity': 'Recent Activity',
    'profile.saved': 'Profile updated successfully',
    'profile.saveFailed': 'Failed to update profile',
    'users.title': 'User Management',
    'users.add': 'Add User',
    'users.username': 'Username',
    'users.displayName': 'Display Name',
    'users.password': 'Password',
    'users.role': 'Role',
    'users.total': 'Total Users',
    'users.owner': 'Owner',
    'users.admin': 'Administrator',
    'users.general': 'General',
    'notif.title': 'Notifications',
    'notif.telegram': 'Telegram Bot',
    'notif.whatsapp': 'WhatsApp Bot',
    'notif.botNumber': 'Bot Phone Number',
    'notif.ownerNumber': 'Owner Number',
    'notif.token': 'Bot Token',
    'notif.chatId': 'Chat ID',
    'notif.connectSave': 'Connect & Save',
    'notif.pairingCode': 'Pairing Code',
    'notif.alerts': 'Alert Rules',
    'plugin.title': 'Plugins',
    'plugin.marketplace': 'Marketplace',
    'plugin.installed': 'Installed',
    'plugin.categories': 'Categories',
    'plugin.dependencies': 'Dependencies',
    'plugin.permissions': 'Permissions',
    'plugin.registry': 'Plugin Registry',
    'plugin.search': 'Search plugins...',
    'plugin.noPlugins': 'No plugins found',
    'logs.title': 'System Logs',
    'logs.refresh': 'Refresh',
    'logs.filter': 'Filter',
    'logs.search': 'Search logs...',
    'logs.autoScroll': 'Auto-scroll',
    'logs.clear': 'Clear',
    'logs.errors': 'errors',
    'logs.warnings': 'warnings',
    'lang.en': 'English',
    'lang.id': 'Bahasa Indonesia',
    'lang.ja': '日本語',
  },
  id: {
    'nav.overview': 'Ringkasan',
    'nav.servers': 'Server',
    'nav.monitoring': 'Pemantauan',
    'nav.analytics': 'Analitik',
    'nav.profile': 'Profil',
    'nav.notifications': 'Notifikasi',
    'nav.automation': 'Otomatisasi',
    'nav.backup': 'Cadangan',
    'nav.tunnel': 'Tunnel',
    'nav.docker': 'Docker',
    'nav.github': 'GitHub',
    'nav.plugins': 'Ekstensi',
    'nav.security': 'Keamanan',
    'nav.audit': 'Audit',
    'nav.users': 'Pengguna',
    'nav.logs': 'Log',
    'nav.settings': 'Pengaturan',
    'nav.main': 'Utama',
    'nav.management': 'Kelola',
    'nav.system': 'Sistem',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Ubah',
    'common.search': 'Cari',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.retry': 'Ulangi',
    'common.back': 'Kembali',
    'common.close': 'Tutup',
    'common.enable': 'Aktifkan',
    'common.disable': 'Nonaktifkan',
    'common.configure': 'Konfigurasi',
    'common.install': 'Pasang',
    'common.uninstall': 'Copot',
    'common.connect': 'Sambungkan',
    'common.disconnect': 'Putuskan',
    'common.refresh': 'Muat Ulang',
    'common.noData': 'Tidak ada data',
    'settings.title': 'Pengaturan',
    'settings.language': 'Bahasa',
    'settings.theme': 'Tema',
    'settings.timezone': 'Zona Waktu',
    'settings.dark': 'Gelap',
    'settings.light': 'Terang',
    'settings.compactMode': 'Mode Padat',
    'settings.animations': 'Animasi',
    'settings.autoRefresh': 'Muat Ulang Otomatis',
    'settings.monitorInterval': 'Interval Pemantauan',
    'settings.sessionTimeout': 'Waktu Sesi',
    'settings.twoFactorAuth': 'Autentikasi Dua Faktor',
    'settings.telegramBot': 'Bot Telegram',
    'settings.whatsappBot': 'Notifikasi WhatsApp',
    'settings.telegramToken': 'Token Bot',
    'settings.telegramChatId': 'ID Chat',
    'settings.waPhoneNumber': 'Nomor WhatsApp',
    'settings.saveSuccess': 'Pengaturan berhasil disimpan',
    'settings.saveFailed': 'Gagal menyimpan pengaturan',
    'settings.unsavedChanges': 'Anda memiliki perubahan yang belum disimpan',
    'profile.title': 'Profil',
    'profile.edit': 'Ubah Profil',
    'profile.fullName': 'Nama Lengkap',
    'profile.email': 'Email',
    'profile.phone': 'Telepon',
    'profile.location': 'Lokasi',
    'profile.bio': 'Bio',
    'profile.department': 'Departemen',
    'profile.avatar': 'Avatar',
    'profile.security': 'Keamanan',
    'profile.devices': 'Perangkat',
    'profile.activity': 'Aktivitas Terbaru',
    'profile.saved': 'Profil berhasil diperbarui',
    'profile.saveFailed': 'Gagal memperbarui profil',
    'users.title': 'Manajemen Pengguna',
    'users.add': 'Tambah Pengguna',
    'users.username': 'Nama Pengguna',
    'users.displayName': 'Nama Tampilan',
    'users.password': 'Kata Sandi',
    'users.role': 'Peran',
    'users.total': 'Total Pengguna',
    'users.owner': 'Pemilik',
    'users.admin': 'Administrator',
    'users.general': 'Umum',
    'notif.title': 'Notifikasi',
    'notif.telegram': 'Bot Telegram',
    'notif.whatsapp': 'Bot WhatsApp',
    'notif.botNumber': 'Nomor Bot',
    'notif.ownerNumber': 'Nomor Pemilik',
    'notif.token': 'Token Bot',
    'notif.chatId': 'ID Chat',
    'notif.connectSave': 'Sambungkan & Simpan',
    'notif.pairingCode': 'Kode Pemasangan',
    'notif.alerts': 'Aturan Peringatan',
    'plugin.title': 'Ekstensi',
    'plugin.marketplace': 'Marketplace',
    'plugin.installed': 'Terpasang',
    'plugin.categories': 'Kategori',
    'plugin.dependencies': 'Ketergantungan',
    'plugin.permissions': 'Izin',
    'plugin.registry': 'Registri Ekstensi',
    'plugin.search': 'Cari ekstensi...',
    'plugin.noPlugins': 'Tidak ada ekstensi',
    'logs.title': 'Log Sistem',
    'logs.refresh': 'Muat Ulang',
    'logs.filter': 'Filter',
    'logs.search': 'Cari log...',
    'logs.autoScroll': 'Gulir Otomatis',
    'logs.clear': 'Bersihkan',
    'logs.errors': 'kesalahan',
    'logs.warnings': 'peringatan',
    'lang.en': 'English',
    'lang.id': 'Bahasa Indonesia',
    'lang.ja': '日本語',
  },
  ja: {
    'nav.overview': '概要',
    'nav.servers': 'サーバー',
    'nav.monitoring': '監視',
    'nav.analytics': '分析',
    'nav.profile': 'プロフィール',
    'nav.notifications': '通知',
    'nav.automation': '自動化',
    'nav.backup': 'バックアップ',
    'nav.tunnel': 'トンネル',
    'nav.docker': 'Docker',
    'nav.github': 'GitHub',
    'nav.plugins': '拡張機能',
    'nav.security': 'セキュリティ',
    'nav.audit': '監査',
    'nav.users': 'ユーザー',
    'nav.logs': 'ログ',
    'nav.settings': '設定',
    'nav.main': 'メイン',
    'nav.management': '管理',
    'nav.system': 'システム',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.search': '検索',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.retry': '再試行',
    'common.back': '戻る',
    'common.close': '閉じる',
    'common.enable': '有効',
    'common.disable': '無効',
    'common.configure': '設定',
    'common.install': 'インストール',
    'common.uninstall': 'アンインストール',
    'common.connect': '接続',
    'common.disconnect': '切断',
    'common.refresh': '更新',
    'common.noData': 'データがありません',
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.theme': 'テーマ',
    'settings.timezone': 'タイムゾーン',
    'settings.dark': 'ダーク',
    'settings.light': 'ライト',
    'settings.compactMode': 'コンパクトモード',
    'settings.animations': 'アニメーション',
    'settings.saveSuccess': '設定を保存しました',
    'settings.saveFailed': '設定の保存に失敗しました',
    'settings.unsavedChanges': '未保存の変更があります',
    'settings.autoRefresh': '自動更新',
    'settings.monitorInterval': '監視間隔',
    'settings.sessionTimeout': 'セッションタイムアウト',
    'settings.twoFactorAuth': '二要素認証',
    'settings.telegramBot': 'Telegram ボット',
    'settings.whatsappBot': 'WhatsApp 通知',
    'settings.telegramToken': 'ボットトークン',
    'settings.telegramChatId': 'チャットID',
    'settings.waPhoneNumber': 'WhatsApp番号',
    'profile.title': 'プロフィール',
    'profile.edit': 'プロフィール編集',
    'profile.fullName': '氏名',
    'profile.email': 'メール',
    'profile.phone': '電話',
    'profile.location': '場所',
    'profile.bio': '自己紹介',
    'profile.department': '部署',
    'profile.avatar': 'アバター',
    'profile.security': 'セキュリティ',
    'profile.devices': 'デバイス',
    'profile.activity': '最近のアクティビティ',
    'profile.saved': 'プロフィールを更新しました',
    'profile.saveFailed': 'プロフィールの更新に失敗しました',
    'users.title': 'ユーザー管理',
    'users.add': 'ユーザー追加',
    'users.username': 'ユーザー名',
    'users.displayName': '表示名',
    'users.password': 'パスワード',
    'users.role': '役割',
    'users.total': '総ユーザー数',
    'users.owner': '所有者',
    'users.admin': '管理者',
    'users.general': '一般',
    'notif.title': '通知',
    'notif.telegram': 'Telegram ボット',
    'notif.whatsapp': 'WhatsApp ボット',
    'notif.botNumber': 'ボット電話番号',
    'notif.ownerNumber': '所有者番号',
    'notif.token': 'ボットトークン',
    'notif.chatId': 'チャットID',
    'notif.connectSave': '接続して保存',
    'notif.pairingCode': 'ペアリングコード',
    'notif.alerts': 'アラートルール',
    'plugin.title': '拡張機能',
    'plugin.marketplace': 'マーケットプレイス',
    'plugin.installed': 'インストール済み',
    'plugin.categories': 'カテゴリー',
    'plugin.dependencies': '依存関係',
    'plugin.permissions': '権限',
    'plugin.registry': '拡張機能レジストリ',
    'plugin.search': '拡張機能を検索...',
    'plugin.noPlugins': '拡張機能が見つかりません',
    'logs.title': 'システムログ',
    'logs.refresh': '更新',
    'logs.filter': 'フィルター',
    'logs.search': 'ログを検索...',
    'logs.autoScroll': '自動スクロール',
    'logs.clear': 'クリア',
    'logs.errors': 'エラー',
    'logs.warnings': '警告',
    'lang.en': 'English',
    'lang.id': 'Bahasa Indonesia',
    'lang.ja': '日本語',
  },
};
const LanguageContext = createContext<LanguageContextValue | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem('mydash-lang');
    return (stored === 'id' || stored === 'en' || stored === 'ja') ? stored : 'id';
  });
  useEffect(() => {
    document.documentElement.lang = lang;
    localStorage.setItem('mydash-lang', lang);
  }, [lang]);
  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('mydash-lang', l);
    document.documentElement.lang = l;
  };
  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  };
  return (
    <LanguageContext value={{ lang, setLang, t }}>
      {children}
    </LanguageContext>
  );
}
export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
