export enum EventCategory {
  System = 'system',
  Performance = 'performance',
  Security = 'security',
  Storage = 'storage',
  Network = 'network',
  Tunnel = 'tunnel',
  Docker = 'docker',
  Database = 'database',
  Redis = 'redis',
  Scheduler = 'scheduler',
  Authentication = 'authentication',
  Notification = 'notification',
  Automation = 'automation',
  GitHub = 'github',
  Backup = 'backup',
  Restore = 'restore',
  Plugin = 'plugin',
  Update = 'update',
  AI = 'ai',
  Audit = 'audit',
}

export enum MetricCategory {
  CPU = 'cpu',
  Memory = 'memory',
  Swap = 'swap',
  Disk = 'disk',
  Filesystem = 'filesystem',
  Network = 'network',
  Docker = 'docker',
  Service = 'service',
  Tunnel = 'tunnel',
  Database = 'database',
  Redis = 'redis',
  Process = 'process',
  Temperature = 'temperature',
}

export enum NotificationCategory {
  Security = 'security',
  Performance = 'performance',
  CPU = 'cpu',
  Memory = 'memory',
  Disk = 'disk',
  Docker = 'docker',
  Tunnel = 'tunnel',
  Network = 'network',
  Database = 'database',
  Redis = 'redis',
  Scheduler = 'scheduler',
  Automation = 'automation',
  GitHub = 'github',
  Backup = 'backup',
  Restore = 'restore',
  Plugin = 'plugin',
  System = 'system',
  AI = 'ai',
  Login = 'login',
  Session = 'session',
}
